volumes:
  nextcloud-data:
#  nextcloud-db:

services:
#  nginx:
#    image: nginx:stable
#    restart: always
#    volumes:
#      - ./nginx/nginx-vhost.conf:/etc/nginx/conf.d/default.conf:ro
#      - ./nginx/certificates:/mycerts
#    ports:
#      - 443:443
#      - 80:80
#    depends_on:
#      - onlyoffice
#      - app

  onlyoffice:
    image: onlyoffice/documentserver
    ports:
      - 8082:80
    environment:
      # Раскомментируйте приведенные ниже строки, чтобы включить проверку веб-токена JSON..
      - JWT_ENABLED=${JWT_ENABLED:-false}
      - JWT_SECRET=${JWT_SECRET:-""}
      - JWT_HEADER=${JWT_HEADER:-""}
      - JWT_IN_BODY=${JWT_IN_BODY:-""}
    restart: always

  nextcloud-db:
    image: postgres:14.1-alpine
    container_name: postgres-nextcloud
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-""}
      - POSTGRES_USER=${POSTGRES_USER:-""}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-""}
    volumes:
#     - nextcloud-db:/var/lib/postgresql/data
     - ./postgres_data:/var/lib/postgresql/data

  app:
    image: nextcloud
    links:
      - nextcloud-db
    volumes:
#      - ./nextcloud:/var/www/html
      - ./apps:/var/www/html/custom_apps
      - ./data:/var/www/html/data
      - ./config:/var/www/html/config
      - nextcloud-data:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER:-""}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD:-""}
      # - NEXTCLOUD_TABLE_PREFIX=${NEXTCLOUD_TABLE_PREFIX:-""}
      - POSTGRES_HOST=${POSTGRES_HOST:-""}
      - POSTGRES_DB=${POSTGRES_DB:-""}
      - POSTGRES_USER=${POSTGRES_USER:-""}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-""}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS:-""}
    ports:
      - 8081:80
    depends_on:
      - nextcloud-db
      - onlyoffice
    restart: always

